services:
  db:
    image: pgvector/pgvector:pg17
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=very_secure_123
    volumes:
      - "./docker/pg-initdb:/docker-entrypoint-initdb.d:ro"
